# 特許データ専用設定
model:
  name: "SakanaAI/TinySwallow-1.5B-Instruct"
  max_seq_length: 2048
  dtype: null
  load_in_4bit: true
  token: null


# LoRA設定（特許データ最適化）
lora:
  r: 32  # 特許データの複雑性に対応
  lora_alpha: 32
  lora_dropout: 0.0
  bias: "none"
  target_modules:
    - "q_proj"
    - "k_proj"
    - "v_proj"
    - "o_proj"
    - "gate_proj"
    - "up_proj"
    - "down_proj"
  use_gradient_checkpointing: "unsloth"
  random_state: 3407
  use_rslora: false
  loftq_config: null

# 特許データセット設定
dataset:
  name: "patent_japanese"
  format: "patent"
  data_files:
    train: "data/processed/patent_train.jsonl"
    validation: "data/processed/patent_val.jsonl"
    test: "data/processed/patent_test.jsonl"
  
  # 特許文書のテンプレート
  instruction_template: |
    以下の特許文書の実施形態を作成してください。

    ### 特許文書:
    {patent_text}

    ### 要約:
  response_template: "{summary}"
  
  # 特許固有の前処理設定
  max_patent_length: 4096
  max_summary_length: 512
  remove_references: true
  clean_formatting: true

# 特許データ用トレーニング設定
training:
  per_device_train_batch_size: 1  # 特許データは長いため削減
  gradient_accumulation_steps: 8
  warmup_steps: 10
  max_steps: 100
  num_train_epochs: null
  learning_rate: 1e-4  # 特許データには低い学習率
  logging_steps: 5
  optim: "adamw_8bit"
  weight_decay: 0.01
  lr_scheduler_type: "cosine"
  seed: 3407
  output_dir: "patent_outputs"
  report_to: "none"
  save_steps: 50
  save_total_limit: 2
  
# 特許データ固有の評価メトリクス
evaluation:
  metrics: ["rouge", "bleu", "patent_similarity"]
  eval_batch_size: 2
  
  # 特許要約評価用設定
  rouge_types: ["rouge1", "rouge2", "rougeL"]
  bleu_max_order: 4
  
# データ前処理設定
preprocessing:
  # 特許文書のセクション
  sections_to_extract: ["abstract", "claims", "description"]
  
  # クリーニングルール
  remove_patterns:
    - "\\[\\d+\\]"  # 参考文献番号
    - "Fig\\. \\d+"  # 図表参照
    - "Table \\d+"   # テーブル参照
  
  # 文字数制限
  min_text_length: 100
  max_text_length: 8000