# TinySwallow モデル専用設定（Google Colab T4 GPU最適化）
base_config: "configs/base_config.yaml"

# モデル固有設定
model:
  name: "SakanaAI/TinySwallow-1.5B-Instruct"
  model_type: "llama"
  tokenizer_name: "SakanaAI/TinySwallow-1.5B-Instruct"
  use_fast_tokenizer: true
  trust_remote_code: false
  max_seq_length: 1024
  dtype: "float16"
  load_in_4bit: true
  token: null

# データセット設定
dataset:
  name: "alpaca_japanese"
  format: "alpaca"
  instruction_template: "以下の指示に従ってください。\n\n### 指示:\n{instruction}\n\n### 応答:\n"
  response_template: "{output}"

# データ設定（下位互換性）
data:
  dataset_name: "yahma/alpaca-cleaned-ja"
  train_split: "train"
  text_field: "text"
  dataset_num_proc: 2
  packing: true

# TinySwallow特有のトレーニング設定（Google Colab T4 GPU最適化）
training:
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  gradient_accumulation_steps: 4
  learning_rate: 0.00005
  num_train_epochs: null
  max_steps: 100
  warmup_steps: 10
  warmup_ratio: null
  lr_scheduler_type: "linear"
  logging_steps: 10
  save_steps: 50
  eval_steps: 50
  save_total_limit: 2
  load_best_model_at_end: false
  metric_for_best_model: "eval_loss"
  greater_is_better: false
  optim: "adamw_torch"
  weight_decay: 0.01
  seed: 42
  output_dir: "/content/drive/MyDrive/tinyswallow_outputs"
  report_to: "none"

# LoRA設定（TinySwallow最適化）
lora:
  r: 16
  alpha: 32
  lora_alpha: 32
  dropout: 0.1
  lora_dropout: 0.1
  target_modules: ["q_proj", "v_proj", "k_proj", "o_proj", "gate_proj", "up_proj", "down_proj"]
  bias: "none"
  task_type: "CAUSAL_LM"
  use_gradient_checkpointing: "unsloth"
  random_state: 42
  use_rslora: false
  loftq_config: null

# 量子化設定
quantization:
  load_in_4bit: true
  bnb_4bit_use_double_quant: true
  bnb_4bit_quant_type: "nf4"
  bnb_4bit_compute_dtype: "float16"

# Unsloth設定
unsloth:
  use_unsloth: true
  max_seq_length: 2048
  dtype: null
  load_in_4bit: true