# TinySwallow モデル専用設定
base_config: "configs/base_config.yaml"

# モデル固有設定
model:
  name: "tokyotech-llm/Swallow-7b-instruct-hf"
  model_type: "swallow"
  tokenizer_name: "tokyotech-llm/Swallow-7b-instruct-hf"
  use_fast_tokenizer: true
  trust_remote_code: true

# データセット設定
dataset:
  name: "alpaca_japanese"
  format: "alpaca"
  instruction_template: "以下の指示に従ってください。\n\n### 指示:\n{instruction}\n\n### 応答:\n"
  response_template: "{output}"

# TinySwallow特有のトレーニング設定
training:
  per_device_train_batch_size: 2
  per_device_eval_batch_size: 2
  gradient_accumulation_steps: 8
  learning_rate: 1e-4
  num_train_epochs: 2
  max_steps: -1
  lr_scheduler_type: "cosine"
  warmup_ratio: 0.03
  logging_steps: 5
  save_steps: 200
  eval_steps: 200
  save_total_limit: 3
  load_best_model_at_end: true
  metric_for_best_model: "eval_loss"
  greater_is_better: false

# LoRA設定（TinySwallow最適化）
lora:
  r: 8
  alpha: 16
  dropout: 0.05
  target_modules: ["q_proj", "v_proj", "k_proj", "o_proj", "gate_proj", "up_proj", "down_proj"]
  bias: "none"
  task_type: "CAUSAL_LM"

# 量子化設定
quantization:
  load_in_4bit: true
  bnb_4bit_use_double_quant: true
  bnb_4bit_quant_type: "nf4"
  bnb_4bit_compute_dtype: "float16"

# Unsloth設定
unsloth:
  use_unsloth: true
  max_seq_length: 2048
  dtype: null
  load_in_4bit: true