# TinySwallow モデル専用設定
# モデル固有設定
model:
  name: "SakanaAI/TinySwallow-1.5B-Instruct"
  tokenizer_name: "SakanaAI/TinySwallow-1.5B-Instruct"
  max_seq_length: 2048
  dtype: null  # 自動検出
  load_in_4bit: true
  token: null  # Hugging Faceのトークナイザーを使用する場合は指定

# データセット設定
dataset:
  name: "alpaca_japanese"
  format: "alpaca"
  instruction_template: "以下の指示に従ってください。\n\n### 指示:\n{instruction}\n\n### 応答:\n"
  response_template: "{output}"

# LoRA設定（TinySwallow最適化）
lora:
  r: 16
  lora_alpha: 16
  lora_dropout: 0.0
  bias: "none"
  target_modules:
    - "q_proj"
    - "k_proj"
    - "v_proj"
    - "o_proj"
    - "gate_proj"
    - "up_proj"
    - "down_proj"
  use_gradient_checkpointing: "unsloth"
  random_state: 3407
  use_rslora: false
  loftq_config: null

# TinySwallow特有のトレーニング設定
training:
  per_device_train_batch_size: 2
  gradient_accumulation_steps: 4
  warmup_steps: 5
  max_steps: 60  # テスト用（本格的には1000+）
  num_train_epochs: null
  learning_rate: 0.0002
  logging_steps: 1
  optim: "adamw_8bit"
  weight_decay: 0.01
  lr_scheduler_type: "linear"
  seed: 3407
  output_dir: "outputs"
  report_to: "none"
  save_steps: null
  save_total_limit: null

# 量子化設定
quantization:
  load_in_4bit: true
  bnb_4bit_use_double_quant: true
  bnb_4bit_quant_type: "nf4"
  bnb_4bit_compute_dtype: "float16"

# Unsloth設定
unsloth:
  use_unsloth: true
  max_seq_length: 2048
  dtype: null
  load_in_4bit: true